<a href="https://colab.research.google.com/github/graceeeem/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
Laboratory 6: Matrix Operations

##Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

###Transposition

$$
A=\begin{bmatrix} 4 & 8 & -2 \\ 6 & -3 & 5 \\ 9 & 3 & 7\end{bmatrix}\\
$$

$$
A^T=\begin{bmatrix} 4 & 6 & 9 \\ 8 & -3 & 3 \\ -2 & 5 & 7\end{bmatrix}\\
$$

np.transpose() or using the T method

In [8]:
G = np.array([
    [1,7,8],
    [3,9,0],
    [4,6,7]
])

In [9]:
GT1 = np.transpose(G)
GT1

array([[1, 3, 4],
       [7, 9, 6],
       [8, 0, 7]])

In [10]:
GT2 = G.T
GT2

array([[1, 3, 4],
       [7, 9, 6],
       [8, 0, 7]])

In [11]:
np.array_equiv(GT1, GT2)

True

In [12]:
R = np.array([
    [1,7,8,5],
    [3,9,0,4]
])
R.shape

(2, 4)

In [14]:
np.transpose(R).shape

(4, 2)

In [16]:
R.T.shape

(4, 2)

##Dot Product/Inner Product

In [19]:
A = np.array([
    [4,-2,4],
    [3,9,1],
    [-1,2,8]
])
C = np.array([
    [2,7,0],
    [3,-9,8],
    [4,-5,1]
])

In [23]:
np.array_equiv(A, C)

False

In [21]:
np.dot(A, C)

array([[ 18,  26, -12],
       [ 37, -65,  73],
       [ 36, -65,  24]])

In [20]:
A.dot(C)

array([[ 18,  26, -12],
       [ 37, -65,  73],
       [ 36, -65,  24]])

In [22]:
A @ C

array([[ 18,  26, -12],
       [ 37, -65,  73],
       [ 36, -65,  24]])

In [24]:
np.matmul(A,C)

array([[ 18,  26, -12],
       [ 37, -65,  73],
       [ 36, -65,  24]])

Rule 1: The inner dimensions of the two matrices in question must be the same.

In [36]:
E = np.array([
    [4,-2,8],
    [1,0,9],
    [-5,1,2],
    [3,9,6]
])
F = np.array([
    [2,7,5],
    [1,3,0],
    [5,8,-2],
    [3,-9,1]
])
G = np.array([
    [1,7],
    [3,9],
    [2,4]
])
print(E.shape)
print(F.shape)
print(G.shape)

(4, 3)
(4, 3)
(3, 2)


In [37]:
E @ G

array([[ 14,  42],
       [ 19,  43],
       [  2, -18],
       [ 42, 126]])

In [38]:
F @ G

array([[ 33,  97],
       [ 10,  34],
       [ 25,  99],
       [-22, -56]])

In [39]:
E @ F

ValueError: ignored

In [40]:
E @ F.T

array([[ 34,  -2, -12,  38],
       [ 47,   1, -13,  12],
       [  7,  -2, -21, -22],
       [ 99,  30,  75, -66]])

Rule 2: Dot Product has special properties

In [ ]:
A = np.array([
    [4,2],
    [5,-1],
    [7,4],
    [2,9]
])
B = np.array([
    [4,1],
    [8,2],
    [-5,2],
    [1,3]
])
C = np.array([
    [1,3],
    [0,-1],
    [6,5],
    [1,4]
])

###Determinant

In [48]:
I = np.array([
    [4,2],
    [9,5]
])
np.linalg.det(I)

2.000000000000001

In [49]:
S = np.array([
    [2,5,-6],
    [4,7,9],
    [-1,8,3]
])
np.linalg.det(S)

-440.9999999999996

do 4X4

###Inverse

In [54]:
B = np.array([
    [3,4],
    [-1, 7]
])

np.array(B @ np.linalg.inv(B), dtype=int)

array([[1, 0],
       [0, 1]])

In [59]:
W = np.array([
              [3, 2, 5, 4],
              [4, 8, -2, 6],
              [4, 8, -2, -2],
              [9, -7, 3, 1]
])
T = np.linalg.inv(W)
T

array([[-1.88679245e-02,  1.83962264e-02,  5.89622642e-02,
         8.30188679e-02],
       [ 5.66037736e-02, -5.18867925e-03,  7.31132075e-02,
        -4.90566038e-02],
       [ 1.88679245e-01, -1.08962264e-01,  3.53773585e-02,
        -3.01886792e-02],
       [-1.57107032e-17,  1.25000000e-01, -1.25000000e-01,
         9.45260641e-18]])

In [60]:
W @ T

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00,
        -3.82293777e-18],
       [-3.87530678e-17,  1.00000000e+00, -5.55111512e-17,
         2.89600629e-17],
       [ 8.69325576e-17,  5.55111512e-17,  1.00000000e+00,
        -4.66607884e-17],
       [-7.12218544e-17, -5.55111512e-17, -5.55111512e-17,
         1.00000000e+00]])